[phases.setup]
nixPkgs = ["python310", "gcc", "libGL", "glib", "xorg.libxcb", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "libSM", "libICE", "ffmpeg"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]
